#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────
# generate-third-party-notices.sh
#
# Generates THIRD_PARTY_NOTICES.md at the repository root by reading
# each vendored library's LICENSE/COPYING file under lib/.
#
# This script is run as part of the Maven build (generate-resources
# phase) so that upgrading a vendored library's license automatically
# flows into the notices file without a manual sync step.
#
# Usage:
#   ./generate-third-party-notices.sh [output-file]
#
# If output-file is not specified, writes to THIRD_PARTY_NOTICES.md in
# the same directory as this script's parent (the repo root).
# ──────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}" && pwd)"
OUTPUT="${1:-${REPO_ROOT}/THIRD_PARTY_NOTICES.md}"

# Each entry: display_name|version|license_type|website|license_file_relative_to_repo
LIBRARIES=(
    "libogg|1.3.6|BSD 3-Clause License|https://xiph.org/ogg/|lib/ogg-1.3.6/COPYING"
    "libvorbis|1.3.7|BSD 3-Clause License|https://xiph.org/vorbis/|lib/vorbis-1.3.7/COPYING"
    "PortAudio|v19.7+|MIT License|http://www.portaudio.com|lib/portaudio/LICENSE.txt"
    "CLAP (CLever Audio Plugin API)|1.2.7|MIT License|https://cleveraudio.org|lib/Clap-1.2.7/LICENSE"
    "FluidSynth|2.5.3|GNU Lesser General Public License (LGPL), version 2.1|https://www.fluidsynth.org|lib/fluidsynth-2.5.3/fluidsynth-2.5.3/LICENSE"
    "LAME (libmp3lame)|3.99.5|GNU Library General Public License (LGPL), version 2|https://lame.sourceforge.io|lib/libmp3lame/COPYING"
    "RoomAcoustiCpp|1.0.1|GNU General Public License (GPL), version 3|https://github.com/audiolabs/RoomAcoustiCpp|lib/RoomAcoustiCpp-1.0.1/RoomAcoustiCpp-1.0.1/LICENSE"
)

{
    cat <<'HEADER'
# Third-Party Notices

This file is auto-generated by `generate-third-party-notices.sh`.
Do not edit manually — update the script or the vendored license files instead.

This project bundles or links to the following third-party native
libraries at runtime. Each library retains its own license; the full
text of each license is reproduced below.

---

HEADER

    INDEX=1
    for entry in "${LIBRARIES[@]}"; do
        IFS='|' read -r NAME VERSION LICENSE WEBSITE LICENSE_FILE <<< "${entry}"
        LICENSE_PATH="${REPO_ROOT}/${LICENSE_FILE}"

        echo "## ${INDEX}. ${NAME}"
        echo ""
        echo "- **Version**: ${VERSION}"
        echo "- **License**: ${LICENSE}"
        echo "- **Website**: ${WEBSITE}"
        echo "- **Source file**: \`${LICENSE_FILE}\`"
        echo ""

        if [[ -f "${LICENSE_PATH}" ]]; then
            echo '```'
            cat "${LICENSE_PATH}"
            echo '```'
        else
            echo "*License file not found at \`${LICENSE_FILE}\`.*"
        fi

        echo ""
        echo "---"
        echo ""
        INDEX=$((INDEX + 1))
    done
} > "${OUTPUT}"

echo "Generated ${OUTPUT}"
