package com.benesquivelmusic.daw.core.audio;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Verifies that THIRD_PARTY_NOTICES.md is present and contains the
 * required attribution text for all vendored native libraries.
 */
class ThirdPartyNoticesTest {

    private static final Path REPO_ROOT = findRepoRoot();

    private static Path findRepoRoot() {
        // Walk up from the current working directory to find the repo root
        // (where THIRD_PARTY_NOTICES.md should live)
        Path dir = Path.of(System.getProperty("user.dir", ".")).toAbsolutePath();
        while (dir != null) {
            if (Files.exists(dir.resolve("pom.xml"))
                    && Files.exists(dir.resolve("daw-core"))) {
                return dir;
            }
            dir = dir.getParent();
        }
        // Fall back to current directory
        return Path.of(".").toAbsolutePath();
    }

    @Test
    void thirdPartyNoticesFileShouldExist() {
        Path noticesFile = REPO_ROOT.resolve("THIRD_PARTY_NOTICES.md");
        assertThat(noticesFile).exists();
    }

    @Test
    void thirdPartyNoticesShouldContainLiboggAttribution() throws IOException {
        String content = Files.readString(REPO_ROOT.resolve("THIRD_PARTY_NOTICES.md"));
        assertThat(content).contains("libogg");
        assertThat(content).contains("BSD 3-Clause");
        assertThat(content).contains("Xiph.org Foundation");
    }

    @Test
    void thirdPartyNoticesShouldContainLibvorbisAttribution() throws IOException {
        String content = Files.readString(REPO_ROOT.resolve("THIRD_PARTY_NOTICES.md"));
        assertThat(content).contains("libvorbis");
        assertThat(content).contains("BSD 3-Clause");
        assertThat(content).contains("Xiph.org Foundation");
    }

    @Test
    void thirdPartyNoticesShouldContainAllVendoredLibraries() throws IOException {
        String content = Files.readString(REPO_ROOT.resolve("THIRD_PARTY_NOTICES.md"));
        assertThat(content).contains("libogg");
        assertThat(content).contains("libvorbis");
        assertThat(content).contains("PortAudio");
        assertThat(content).contains("CLAP");
        assertThat(content).contains("FluidSynth");
        assertThat(content).contains("LAME");
        assertThat(content).contains("RoomAcoustiCpp");
    }

    @Test
    void thirdPartyNoticesShouldContainVerbatimLicenseText() throws IOException {
        String content = Files.readString(REPO_ROOT.resolve("THIRD_PARTY_NOTICES.md"));
        // Verify the full BSD 3-clause copyright notices are present verbatim
        assertThat(content).contains(
                "Redistributions in binary form must reproduce the above copyright");
        assertThat(content).contains(
                "Permission is hereby granted, free of charge");
    }

    @Test
    void thirdPartyNoticesShouldBeAutoGenerated() throws IOException {
        String content = Files.readString(REPO_ROOT.resolve("THIRD_PARTY_NOTICES.md"));
        assertThat(content).contains("auto-generated by");
    }
}
