package com.benesquivelmusic.daw.core.audio;

import com.benesquivelmusic.daw.core.mastering.CrossfadeGenerator;
import com.benesquivelmusic.daw.sdk.mastering.CrossfadeCurve;

import java.util.Objects;

/**
 * Processes audio through a crossfade region between two overlapping clips.
 *
 * <p>During playback, when the playhead is in the crossfade region, this
 * processor applies gain curves generated by {@link CrossfadeGenerator} to
 * the outgoing and incoming clip audio and sums them into the output buffer.</p>
 */
public final class ClipCrossfadeProcessor {

    private ClipCrossfadeProcessor() {
        // utility class
    }

    /**
     * Applies crossfade gain curves to overlapping audio and writes the
     * blended result into the output buffer.
     *
     * <p>The outgoing audio is multiplied by the fade-out curve and the
     * incoming audio is multiplied by the fade-in curve. The two are then
     * summed sample-by-sample into the output.</p>
     *
     * <p>All three buffers must have the same dimensions
     * ({@code [channels][samples]}) and contain at least {@code numSamples}
     * samples per channel.</p>
     *
     * @param curveType     the crossfade curve type
     * @param outgoingAudio the audio from the outgoing clip {@code [channel][sample]}
     * @param incomingAudio the audio from the incoming clip {@code [channel][sample]}
     * @param output        the output buffer to write into {@code [channel][sample]}
     * @param numSamples    the number of samples in the crossfade region
     * @throws NullPointerException     if any argument is {@code null}
     * @throws IllegalArgumentException if numSamples is not positive or if
     *                                  the buffers have mismatched channel counts
     */
    public static void process(CrossfadeCurve curveType,
                               float[][] outgoingAudio,
                               float[][] incomingAudio,
                               float[][] output,
                               int numSamples) {
        Objects.requireNonNull(curveType, "curveType must not be null");
        Objects.requireNonNull(outgoingAudio, "outgoingAudio must not be null");
        Objects.requireNonNull(incomingAudio, "incomingAudio must not be null");
        Objects.requireNonNull(output, "output must not be null");

        if (numSamples <= 0) {
            throw new IllegalArgumentException("numSamples must be positive: " + numSamples);
        }
        if (outgoingAudio.length != incomingAudio.length
                || outgoingAudio.length != output.length) {
            throw new IllegalArgumentException(
                    "all buffers must have the same number of channels");
        }

        float[][] curves = CrossfadeGenerator.generate(curveType, numSamples);
        float[] fadeOut = curves[0];
        float[] fadeIn = curves[1];

        int channels = output.length;
        for (int ch = 0; ch < channels; ch++) {
            for (int i = 0; i < numSamples; i++) {
                output[ch][i] = outgoingAudio[ch][i] * fadeOut[i]
                        + incomingAudio[ch][i] * fadeIn[i];
            }
        }
    }
}
